(define add1 (lambda (x)
	       (+ 1 x)))
(define (mines1 x )
		(- x 1))
(define pi (* 4 (atan 1.0)))
(define 2pi (lambda (x)
              (* pi (/ x 180))))
(define S (lambda (v t)
            (* v t)))
(define g 9.8)
(define t (lambda (v)
            (/ (* 2 v) g)))
